/**
 * CSSR Backend
 * A REST backend for the CSSR application
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as querystring from "querystring";
import * as url from "url";



export interface Dictionary<T> { [index: string]: T; }
export const defaultHeaders : Dictionary<string> = { };
export let BASE_PATH = "https://localhost:8090/".replace(/\/+$/, "");

export interface FetchArgs {
    url: string;
    options: RequestInit;
}

export class BaseAPI {
    basePath: string;

    constructor(basePath?: string) {
        if(!basePath) {
            basePath = BASE_PATH;
        }
        this.basePath = basePath;
    }
};

export interface IterableUser {
}

export interface Presentation {
    "abstract"?: string;
    "dateTime"?: Timestamp;
    "location"?: string;
    "presentationId"?: number;
    "speakerId"?: number;
    "title"?: string;
}

export interface Principal {
    "name"?: string;
}

export interface Timestamp {
    "date"?: number;
    "day"?: number;
    "hours"?: number;
    "minutes"?: number;
    "month"?: number;
    "nanos"?: number;
    "seconds"?: number;
    "time"?: number;
    "timezoneOffset"?: number;
    "year"?: number;
}

export interface User {
    "displayName"?: string;
    "email"?: string;
    "passwordEnc"?: string;
    "tempToken"?: string;
    "tempTokenExpiresAt"?: Timestamp;
    "userId"?: number;
}



/**
 * PresentationcontrollerApi - fetch parameter creator
 */
export const PresentationcontrollerApiFetchParamCreator = {
    /** 
     * addPresentation
     * @param pres pres
     */
    addPresentationUsingPOST(params: {  "pres": Presentation; }, options?: any): FetchArgs {
        // verify required parameter "pres" is set
        if (params["pres"] == null) {
            throw new Error("Missing required parameter pres when calling addPresentationUsingPOST");
        }
        const baseUrl = `/presentation`;
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = Object.assign({}, { method: "POST" }, options);

        let contentTypeHeader: Dictionary<string> = Object.assign({}, defaultHeaders);
        contentTypeHeader = { "Content-Type": "application/json" };
        if (params["pres"]) {
            fetchOptions.body = JSON.stringify(params["pres"] || {});
        }
        if (contentTypeHeader) {
            fetchOptions.headers = contentTypeHeader;
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
    /** 
     * getFuture
     */
    getFutureUsingGET(options?: any): FetchArgs {
        const baseUrl = `/presentation`;
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = Object.assign({}, { method: "GET" }, options);

        let contentTypeHeader: Dictionary<string> = Object.assign({}, defaultHeaders);
        if (contentTypeHeader) {
            fetchOptions.headers = contentTypeHeader;
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
};

/**
 * PresentationcontrollerApi - functional programming interface
 */
export const PresentationcontrollerApiFp = {
    /** 
     * addPresentation
     * @param pres pres
     */
    addPresentationUsingPOST(params: { "pres": Presentation;  }, options?: any): (basePath?: string) => Promise<Presentation> {
        const fetchArgs = PresentationcontrollerApiFetchParamCreator.addPresentationUsingPOST(params, options);
        return (basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return <Promise<Presentation>>response.json();
                } else {
                    throw response;
                }
            });
        };
    },
    /** 
     * getFuture
     */
    getFutureUsingGET(options?: any): (basePath?: string) => Promise<Array<Presentation>> {
        const fetchArgs = PresentationcontrollerApiFetchParamCreator.getFutureUsingGET(options);
        return (basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return <Promise<Array<Presentation>>>response.json();
                } else {
                    throw response;
                }
            });
        };
    },
};

/**
 * PresentationcontrollerApi - object-oriented interface
 */
export class PresentationcontrollerApi extends BaseAPI {
    /** 
     * addPresentation
     * @param pres pres
     */
    addPresentationUsingPOST(params: {  "pres": Presentation; }, options?: any) {
        return PresentationcontrollerApiFp.addPresentationUsingPOST(params, options)(this.basePath);
    }
    /** 
     * getFuture
     */
    getFutureUsingGET(options?: any) {
        return PresentationcontrollerApiFp.getFutureUsingGET(options)(this.basePath);
    }
};

/**
 * PresentationcontrollerApi - factory interface
 */
export const PresentationcontrollerApiFactory = function (basePath?: string) {
    return {
        /** 
         * addPresentation
         * @param pres pres
         */
        addPresentationUsingPOST(params: {  "pres": Presentation; }, options?: any) {
            return PresentationcontrollerApiFp.addPresentationUsingPOST(params, options)(basePath);
        },
        /** 
         * getFuture
         */
        getFutureUsingGET(options?: any) {
            return PresentationcontrollerApiFp.getFutureUsingGET(options)(basePath);
        },
    };
};


/**
 * TestcontrollerApi - fetch parameter creator
 */
export const TestcontrollerApiFetchParamCreator = {
    /** 
     * GetTest
     * @param name name
     */
    getTestUsingGET(params: {  "name"?: string; }, options?: any): FetchArgs {
        const baseUrl = `/test`;
        let urlObj = url.parse(baseUrl, true);
        urlObj.query = Object.assign({}, urlObj.query, {
            "name": params["name"],
        });
        let fetchOptions: RequestInit = Object.assign({}, { method: "GET" }, options);

        let contentTypeHeader: Dictionary<string> = Object.assign({}, defaultHeaders);
        if (contentTypeHeader) {
            fetchOptions.headers = contentTypeHeader;
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
    /** 
     * GetUser
     */
    getUserUsingGET(options?: any): FetchArgs {
        const baseUrl = `/test/user`;
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = Object.assign({}, { method: "GET" }, options);

        let contentTypeHeader: Dictionary<string> = Object.assign({}, defaultHeaders);
        if (contentTypeHeader) {
            fetchOptions.headers = contentTypeHeader;
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
};

/**
 * TestcontrollerApi - functional programming interface
 */
export const TestcontrollerApiFp = {
    /** 
     * GetTest
     * @param name name
     */
    getTestUsingGET(params: { "name"?: string;  }, options?: any): (basePath?: string) => Promise<string> {
        const fetchArgs = TestcontrollerApiFetchParamCreator.getTestUsingGET(params, options);
        return (basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return <Promise<string>>response.json();
                } else {
                    throw response;
                }
            });
        };
    },
    /** 
     * GetUser
     */
    getUserUsingGET(options?: any): (basePath?: string) => Promise<Principal> {
        const fetchArgs = TestcontrollerApiFetchParamCreator.getUserUsingGET(options);
        return (basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return <Promise<Principal>>response.json();
                } else {
                    throw response;
                }
            });
        };
    },
};

/**
 * TestcontrollerApi - object-oriented interface
 */
export class TestcontrollerApi extends BaseAPI {
    /** 
     * GetTest
     * @param name name
     */
    getTestUsingGET(params: {  "name"?: string; }, options?: any) {
        return TestcontrollerApiFp.getTestUsingGET(params, options)(this.basePath);
    }
    /** 
     * GetUser
     */
    getUserUsingGET(options?: any) {
        return TestcontrollerApiFp.getUserUsingGET(options)(this.basePath);
    }
};

/**
 * TestcontrollerApi - factory interface
 */
export const TestcontrollerApiFactory = function (basePath?: string) {
    return {
        /** 
         * GetTest
         * @param name name
         */
        getTestUsingGET(params: {  "name"?: string; }, options?: any) {
            return TestcontrollerApiFp.getTestUsingGET(params, options)(basePath);
        },
        /** 
         * GetUser
         */
        getUserUsingGET(options?: any) {
            return TestcontrollerApiFp.getUserUsingGET(options)(basePath);
        },
    };
};


/**
 * UsercontrollerApi - fetch parameter creator
 */
export const UsercontrollerApiFetchParamCreator = {
    /** 
     * getAll
     */
    getAllUsingGET(options?: any): FetchArgs {
        const baseUrl = `/user`;
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = Object.assign({}, { method: "GET" }, options);

        let contentTypeHeader: Dictionary<string> = Object.assign({}, defaultHeaders);
        if (contentTypeHeader) {
            fetchOptions.headers = contentTypeHeader;
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
};

/**
 * UsercontrollerApi - functional programming interface
 */
export const UsercontrollerApiFp = {
    /** 
     * getAll
     */
    getAllUsingGET(options?: any): (basePath?: string) => Promise<IterableUser> {
        const fetchArgs = UsercontrollerApiFetchParamCreator.getAllUsingGET(options);
        return (basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return <Promise<IterableUser>>response.json();
                } else {
                    throw response;
                }
            });
        };
    },
};

/**
 * UsercontrollerApi - object-oriented interface
 */
export class UsercontrollerApi extends BaseAPI {
    /** 
     * getAll
     */
    getAllUsingGET(options?: any) {
        return UsercontrollerApiFp.getAllUsingGET(options)(this.basePath);
    }
};

/**
 * UsercontrollerApi - factory interface
 */
export const UsercontrollerApiFactory = function (basePath?: string) {
    return {
        /** 
         * getAll
         */
        getAllUsingGET(options?: any) {
            return UsercontrollerApiFp.getAllUsingGET(options)(basePath);
        },
    };
};

